apiVersion: v1
kind: Pod
metadata:
  name: boyce-pod-test
spec:
  containers:
    - name: boyce-test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: database-password

  restartPolicy: Never
