# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2    
    - uses: actions/checkout@v1          

    - name: Build & Push the container image
      env:
        registry: ${{ secrets.OPENSHIFT_REGISTRY }}
        registry_password: ${{ secrets.OPENSHIFT_API_TOKEN }}
        openshift_project: fl-project
        image_name: ${{ github.repository }}
        image_tag: ${{ github.ref }}
      run: |
        docker build -t $registry/$openshift_project/${image_name##*/}:${image_tag##*/} .
        docker login -u the_user_dont_matter -p $registry_passowrd $registry
        docker push $registry/$openshift_project/${image_name##*/}:${image_tag##*/}
        
    # BUG - Impossible de rediriger l'output ou de piper. 
    # https://github.com/redhat-developer/openshift-actions/issues/13
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v1.1
      with:
        version: 'latest'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |          
          'version'
          'registry info'
          'project'
